package com.example.coffeegeek.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.Table;

public class Test extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout HorizontalLayout_2;
	@AutoGenerated
	private RichTextArea RichTextArea_1;
	@AutoGenerated
	private Table Table_1;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public Test() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();

		// top-level component properties
		setHeight("100.0%");
		setWidth("100.0%");

		// HorizontalLayout_2
		HorizontalLayout_2 = buildHorizontalLayout_2();
		HorizontalLayout_2.setImmediate(false);
		HorizontalLayout_2.setHeight("-1px");
		HorizontalLayout_2.setWidth("-1px");
		mainLayout.addComponent(HorizontalLayout_2);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		HorizontalLayout_2 = new HorizontalLayout();

		// Table_1
		Table_1 = new Table();
		Table_1.setImmediate(false);
		Table_1.setHeight("-1px");
		Table_1.setWidth("-1px");
		HorizontalLayout_2.addComponent(Table_1);

		// RichTextArea_1
		RichTextArea_1 = new RichTextArea();
		RichTextArea_1.setImmediate(false);
		RichTextArea_1.setHeight("-1px");
		RichTextArea_1.setWidth("-1px");
		HorizontalLayout_2.addComponent(RichTextArea_1);

		return HorizontalLayout_2;
	}

}
